### PR TITLE
Tray

### LINKED ISSUE #19: Add more tray features
Currently, the tray has only toggle show/hide and close button.
We need -
* Play/Pause
* Restart
* Hovering over the tray icon should display the name of the song
* Set preferences from the tray.

You can send separate PRs if needed.

### PR DESCRIPTION
**Pull request by blukai**
closes #19 

image

image

### CODE REVIEW

**Comment by anshumanv** [comment]
Thanks so much for this @blukai 😄 
Works awesome 👍 
Perhaps is there a way to see whether what preferences are selected in the system tray?

**Comment by blukai** [comment]
@anshumanv Sure, I'll add indicators. 🍀

**Comment by anshumanv** [comment]
Thanks for the quick addition. 🍀 
Works amazing!
Keep sending such 🔝 quality PRs. 😄

**Comment by anshumanv** [comment]
Please join - https://gitter.im/ongaku-desktop/Lobby# for further discussing on how to enhance it. 😄

**Pull request merged**
