### PR TITLE
Design app icon

### PR DESCRIPTION
**Pull request by ismaeldcom**
In reference of #14 I just upload an app icon in 256x256 for executable and all tray icons updated.

I hope you like it :)

Cheers

### CODE REVIEW

**Comment by anshumanv** [comment]
Hey, thanks so much for this!
Perhaps would it look well if we make the background transparent?

**Comment by ismaeldcom** [comment]
Hi @anshumanv,

Here you can see how it look with transparent background and a tiny sample to see how it merge with some colors.

ongaku-transparent
ongaku-sample

**Comment by anshumanv** [comment]
Thanks so much for this @ismaeldcom! 😄 
Transparent looks awesome to me, please replace all icons with transparent since it will look good on the system tray when the app is running. 👍

**Comment by anshumanv** [comment]
Thanks for the quick fix @ismaeldcom 😄 
Everything is perfect! 👍 
Cheers!

**Comment by ismaeldcom** [comment]
I'm glad you like it @anshumanv

**Comment by anshumanv** [comment]
That's some real burden off my shoulders, I'll replace the icons in the app right away.
Also, do let me know if you wanna design more icons 😉

**Pull request merged**
