### PR TITLE
Add play, pause, restart tray features - fixes #19

### LINKED ISSUE #19: Add more tray features
Currently, the tray has only toggle show/hide and close button.
We need -
* Play/Pause
* Restart
* Hovering over the tray icon should display the name of the song
* Set preferences from the tray.

You can send separate PRs if needed.

### PR DESCRIPTION
**Pull request by zdoc01**
I haven't done any testing on Windows yet, but I wanted to throw up the PR to get some feedback. I'll update with any changes necessary to accommodate Windows shortly. Let me know what you think of the approach!

P.S. - There's a small bug where the first song doesn't update the tray tooltip. This appears to be because the event listeners in the preload script are added _after_ the first song is triggered by the web app (so it never propagates to the tray). I'm still investigating how to get around that, but let me know if you have any thoughts.

### CODE REVIEW

**Comment by anshumanv** [comment]
Hey thanks so much for your hard work on this @zdoc01 
It works flawlessly! 👍 
However, I'm in a dilemma here as #23 fixes this and also the guy claimed the issue so, I have to merge that.
However #19 doesn't cover the `Play Next` and `Play Previous` button so if you could work on that then it would be awesome. 😄

**Comment by anshumanv** [comment]
Btw please join - https://gitter.im/ongaku-desktop/Lobby# for further discussions about the project. 😄

**Comment by zdoc01** [comment]
@anshumanv - np! I had already started looking into these changes and didn't realize another PR had been open. Sorry for the confusion!

**Comment by anshumanv** [comment]
No worries!
Looking forward to more contributions from you! :smile:

**Pull request closed without merging**
